dist: bionic
language: python

addons:
  apt:
    packages:
      - gcc
      - g++

python:
  - "3.6"
  - "3.7"

cache: pip

install:
  - pip install -q cython
  - pip install .

script:
  - python test.py

branches:
  only:
    - travis

notifications:
  email: false
