language: python

addons:
  apt:
    packages:
      - gcc
      - g++

matrix:
  include:
    - name: "Python 3.7 on Bionic Linux"
      python: "3.7"
      dist: bionic
    - name: "Python 3.6 on Bionic Linux"
      python: "3.6"
      dist: bionic
    - name: "Python 3.7 on Xenial Linux"
      python: "3.7"
      dist: xenial
    - name: "Python 3.6 on Xenial Linux"
      python: "3.6"
      dist: xenial

cache: pip

install:
  - pip install -q cython
  - pip install .

script:
  - python test.py

notifications:
  email: false
